route:
  repeat_interval: 2h
  receiver: email-1
  routes:
    - match:
        alertname: httpd_down
      receiver: email-1

    - match:
        alertname: nginx_down
      receiver: email-1

receivers:
- name: email-1
  email_configs:
  - to: 1621740748@qq.com
    from: 1621740748@qq.com
    smarthost: smtp.qq.com:465
    auth_username: "1621740748@qq.com"
    auth_identity: "1621740748@qq.com"
    auth_password: "okqctdndlbzhcgfa"

